Repository stellar/js-stellar-base, pull requests merged in 2023-07, with the labels that each got.

#642 Fix Preview 10 contract invoke & Release `v10.0.0-soroban.3`
  package.json
  src/contract.js
  test/unit/contract_test.js
Labels: soroban-scrum, preview-10

#645 Make opinionated judgements about string/symbol decoding
  src/scval.js
  test/unit/scval_test.js
Labels: bug, soroban-scrum

#660 Add `TransactionBuilder.setFootprint()` method to prepare footprint easily
  src/index.js
  src/operations/restore_footprint.js
  src/sorobandata_builder.js
  src/transaction_builder.js
  test/unit/sorobandata_builder_test.js
  types/index.d.ts
Labels: soroban-scrum
